// This code was automatically generated by Unity Editor script.

public class Test1
{
     public System.Int32 ID { get; set;}
     public System.String Name { get; set;}
     public System.Int32[] Damage { get; set;}
     public System.Single Speed { get; set;}
     public System.Boolean IsTest { get; set;}
     public UnityEngine.Vector3 TestName { get; set;}
     public UnityEngine.Vector3[] TestName2 { get; set;}
     public UnityEngine.Color TestName3 { get; set;}
}
