// This code was automatically generated by Unity Editor script.

public class Test2
{
     public System.Int32 ID { get; set;}
     public System.String Name { get; set;}
     public System.Int32[] Damage { get; set;}
     public System.Single Speed { get; set;}
     public System.Boolean IsTest { get; set;}
     public System.String[] TestName { get; set;}
}
