using System;
using System.Data;
using UnityEditor;
using UnityEngine;

namespace FastDev
{
    public static class ExcelToCS
    {
        public static void Generate(DataTable dataTable)
        {
            string path = Application.dataPath + "/FastDev/GeneratedCode/";
            if (!System.IO.Directory.Exists(path))
            {
                System.IO.Directory.CreateDirectory(path);
            }

            string csName = dataTable.TableName;

            string filePath = path + $"{csName}.cs";
            System.IO.StreamWriter writer = new System.IO.StreamWriter(filePath);
            writer.WriteLine("// This code was automatically generated by Unity Editor script.");
            writer.WriteLine("using UnityEngine;");
            writer.WriteLine("using FastDev;");
            writer.WriteLine();


            writer.WriteLine($"public class {csName}");

            writer.WriteLine("{");

            for (int j = 0; j < dataTable.Columns.Count; j++)
            {
                string columnName = dataTable.Rows[0][j].ToString();
                string typeStr = dataTable.Rows[1][j].ToString();

                Type type = ExcelHelper.GetTypeByString(typeStr);

                writer.WriteLine($"     public {type} {columnName} {{ get; set;}}");
            }

            writer.WriteLine("}");
            writer.Close();

            AssetDatabase.Refresh();
        }
    }
}
